### ISSUE TITLE
Eliminar jar de PostgreSQL i MYSQL del war de BACK

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/pinbaladmin#253]
Dins del back hi ha referències a postgreSQl i MYSQL. Eliminar-les

![imatge](https://github.com/user-attachments/assets/af75460c-d4a9-48b6-b21d-4819a433f055)

**Comment by ptrias-fundaciobit** [comment]
Abans:
pinbaladmin.ear 48.536 KB

Despres
pinbaladmin.ear 46.852 KB
