### ISSUE TITLE
Error en el filtre de la pantalla de sol.licituds locals

### ISSUE THREAD

**Issue by atrobat-dgtic** [Fundacio-Bit/pinbaladmin#37]
Si filtram entre dues dates donat un error: 

Error:org.springframework.validation.BeanPropertyBindingResult: 2 errors Field error in object 'solicitudFilterForm' on field 'estatIDDesde': rejected value [01/10/2021]; codes [typeMismatch.solicitudFilterForm.estatIDDesde,typeMismatch.estatIDDesde,typeMismatch.java.lang.Long,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [solicitudFilterForm.estatIDDesde,estatIDDesde]; arguments []; default message [estatIDDesde]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Long' for property 'estatIDDesde'; nested exception is java.lang.NumberFormatException: For input string: "01/10/2021"] Field error in object 'solicitudFilterForm' on field 'estatIDFins': rejected value [31/10/2021]; codes [typeMismatch.solicitudFilterForm.estatIDFins,typeMismatch.estatIDFins,typeMismatch.java.lang.Long,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [solicitudFilterForm.estatIDFins,estatIDFins]; arguments []; default message [estatIDFins]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Long' for property 'estatIDFins'; nested exception is java.lang.NumberFormatException: For input string: "31/10/2021"] (/pinbaladmin/operador/solicitudlocal/list/1)

**Comment by atrobat-dgtic** [comment]
També passa  a la pantalla de sol.licituds estatals.

**Comment by anadal-fundaciobit** [comment]
Bones. En camp EstatID és un valor sencer !!! No és una data. Com que és un valor sencer, el pots filtar entre dos números.

**Comment by anadal-fundaciobit** [comment]
Estat és un codi numèric i tu estàs posant una data. En agrupacio ja  hi ha per agrupar per DATA
